[package]
name = "tabfile"
version = "0.1.0"
authors = ["Jörn Bethune"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
tempfile = "3"
